### ISSUE TITLE
[Melhoria] Organizar estrutura das pastas melhor

### ISSUE THREAD

**Issue by nawarian** [Elissdev/Testes-do-Firefly#29]
Hoje você tem 7 pastas, com 1 arquivo cada uma:

```
caso-1/
caso-2/
caso-3/
caso-4/
caso-5/
caso-6/
caso-7/
```

Imagine que eu sou uma pessoa que nunca teve contato com este projeto e me dão a tarefa de "executar o caso de testes de adicionar conta de passivos". Como é que eu acho este caso de testes olhando pra essa lista de pastas? Como melhorar esta estrutura para que fique mais fácil de encontrar?

**Comment by Elissdev** [comment]
Issue resolvida.

**Comment by Elissdev** [comment]
Estrutura organizada!
